### PR TITLE
Add publishing pipeline builds (release-0.0)

### PR DESCRIPTION
**Pull request by suskin**
## Overview

This adds Jenkinsfiles for our publishing pipeline:

* `Jenkinsfile.tag`, for tagging commits
* `Jenkinsfile.publish`, for publishing commits to dockerhub
* `Jenkinsfile.branch`, for creating release branches

The Jenkinsfiles are identical to the ones in #33 .

It's intended to be used in the [upbound Jenkins](https://jenkinsci.upbound.io/job/crossplaneio/job/sample-stack-wordpress), and is similar to existing publishing pipelines.

There are two types of builds:

* Continuous, from master, whenever a commit is pushed
* On-demand, from a release branch

This adds the functionality for both, but we will need additional setup to trigger the builds when a commit is pushed:

* [ ] Configure a webhook to trigger the build for the master branch

Also, out of scope are labeled channel updates (such as `alpha`).

Note that some additional work will probably be needed in order to fit this into the template stacks version of the stack.

## Testing done

I've done a bunch of testing in the [upbound Jenkins](https://jenkinsci.upbound.io/job/crossplaneio/job/sample-stack-wordpress), with a private dockerhub repository. I've done tagging and publishing and seen them succeed.

## After this is merged

After this is merged, we'll need to clean up the existing job and try out the process:

* [ ] Point the job back at `crossplaneio` instead of `suskin`
* [ ] Run a release of `0.0.1` using the new jobs
* [x] Document the new release process

### CODE REVIEW

**Comment by suskin** [comment]
Since this is specific to the pre-template stack, I'm going to change this to point at `release-0.0`, which has the pre-template stack code.

**Comment by muvaf** [comment]
> Since this is specific to the pre-template stack, I'm going to change this to point at release-0.0, which has the pre-template stack code.

I am not sure whether that's something we should address. I think there will be a repo for pre-template stacks version that we can refer to as opposed to an old commit in this repo. We can build the pipeline in that repo instead of here.

**Comment by suskin** [comment]
> > Since this is specific to the pre-template stack, I'm going to change this to point at release-0.0, which has the pre-template stack code.
> 
> I am not sure whether that's something we should address. I think there will be a repo for pre-template stacks version that we can refer to as opposed to an old commit in this repo. We can build the pipeline in that repo instead of here.

Yeah, the idea with putting it in this branch is that we can use the old version as a test for the pipeline. I'm not sure when we'll create the repo for the controller variation of the wordpress stack. It isn't something which I sought to address just to address it; it's something that happens to be convenient in the course of creating the pipeline, and which is a good exercise of the system.

**Review by displague — APPROVED** [review]
I don't have a strong opinion about whether or not the old release includes these changes.  Doing so doesn't conflict, imho, with my thoughts on the other PR https://github.com/crossplaneio/sample-stack-wordpress/pull/33#discussion_r380915100

**Pull request merged**
