### PR TITLE
Create resources in the same namespace with WordpressInstance.

### PR DESCRIPTION
**Pull request by muvaf**
Create resources in the same namespace with WordpressInstance.

Signed-off-by: Muvaffak Onus <onus.muvaffak@gmail.com>

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
This looks good to me @muvaf, thanks for this fix!! 

were you able to run `make integration-test`?

i'll defer to @suskin to approve this change.

**Comment by suskin** [comment]
Nice! Thanks @muvaf ! Could you also describe what testing has been done? That way, as reviewers, we can have some more confidence in the change without having to test it as much ourselves : ). There is a `make integration-test` that you should be able to run which should help with testing.

I have a couple hygiene comments which I don't feel strongly about in this case, but which I will probably get more strict about at some point in the future : )

The hygiene comments are below.

Could you add a bit more detail to the commit message? Here's the formula I've been using:

```
category: one-line summary of change

This section down here is longer, and is an explanation
of why the change is being made, or why it is happening
in the way it is being done. The goal of this section is to
help people get into the mindset of the original author, so
that they can keep making changes in the way that the
original author would be, if that's what they want to do.

commit signature
```

I have also been using [verified commit signatures](https://help.github.com/en/articles/about-commit-signature-verification), which I am not sure I am seeing on this commit. Could you set that up? I believe this is a thing which is common across all Crossplane projects.

**Comment by suskin** [comment]
@jbw976 and I are doing some integration testing of some other changes, so I'm going to merge this so we can include it in that testing. If we find any issues, we'll make some fixes and create a new code review for that.

**Review by suskin — APPROVED** [review]

**Comment by suskin** [comment]
I've relaxed the repo constraint of requiring signed commits so that we can merge this, but I am thinking that we'll want to consider reenabling it in the future.

**Pull request merged**
