### PR TITLE
k8s target: update kubernetesapplication to schedule to k8s target

### PR DESCRIPTION
**Pull request by hasheddan**
Minor change to use `KubernetesTarget` instead of `KubernetesCluster` for scheduling the Wordpress `KubernetesAppliation`. Also updates `Crossplane` dependency to v0.7.0 and `crossplane-runtime` to `v0.4.0`.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

### CODE REVIEW

**Comment by hasheddan** [comment]
Tested with the following:

1. Installled Crossplane and stack-gcp.
2. Dynamically provisioned `MySQLInstance` and `KubernetesCluster`:
```yaml
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstanceClass
metadata:
  name: cloudsqlinstancemysql-standard
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    databaseVersion: MYSQL_5_6
    region: us-west2
    settings:
      tier: db-n1-standard-1
      dataDiskType: PD_SSD
      dataDiskSizeGb: 10
      ipConfiguration:
        ipv4Enabled: true
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete
---
apiVersion: database.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: app-mysql
spec:
  classSelector:
    matchLabels:
      example: "true"
  writeConnectionSecretToRef:
    name: mysqlconn
  engineVersion: "5.6"
---
apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GKEClusterClass
metadata:
  name: gkecluster-standard
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  machineType: n1-standard-1
  numNodes: 1
  zone: us-central1-b
  providerRef:
    name: gcp-provider
  reclaimPolicy: Delete
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: app-kubernetes
spec:
  classSelector:
    matchLabels:
      example: "true"
  writeConnectionSecretToRef:
    name: k8scluster
```
3. Created `WordpressInstance` with explicit references to the MySQL and K8s claims:
```
apiVersion: wordpress.samples.stacks.crossplane.io/v1alpha1
kind: WordpressInstance
metadata:
  name: wordpressinstance-sample
spec:
  mySQLInstanceRef:
    name: app-mysql
    namespace: default
  kubernetesClusterRef:
    name: app-kubernetes
    namespace: default
```
4. The following are true:
 - The labels that are added to the referenced or created `KubernetesCluster` claim by the Wordpress controller were successfully propagated to the corresponding `KubernetesTarget` owned by the `KubernetesCluster` claim.
  - The `KubernetesApplication` was successfully scheduled to the `KubernetesTarget` using the labels that were propagated.
  - All resources in the `KubernetesApplication` were successfully deployed into the remote k8s cluster (verified by connecting to the remote cluster directly).
  - The MySQL connection `Secret` was successfully propagated to the remote k8s cluster.

**Review by negz — APPROVED** [review]

**Comment by hasheddan** [comment]
Will wait for approval from @suskin before merging here, given that he has the most experience with this stack.

**Review by suskin — APPROVED** [review]
Looks pretty good to me!

I have a couple comments which I wouldn't really consider blockers:

* Is this new functionality that we should be documenting in this repo? If so, I am thinking it's totally fine for it to be a separate PR.
* Did we already test to make sure none of the other functionality has regressed? (As in, provisioning by binding with configured classes.) Ideally we'd have this automated so it's more convenient, but `make integration-test` can be used to do some of the work for you. Since it's a small change it seems like this **may** not be needed (that's why I don't consider this a blocker), but it's a good habit since you never know for sure until you see the test succeed.

Thanks @hasheddan for making this change!

**Comment by prasek** [comment]
@hasheddan suggest changing `kubernetesClusterRef` this to `kubernetesTargetRef` here.

```
apiVersion: wordpress.samples.stacks.crossplane.io/v1alpha1
kind: WordpressInstance
metadata:
  name: wordpressinstance-sample
spec:
  mySQLInstanceRef:
    name: app-mysql
    namespace: default
  kubernetesClusterRef:
    name: app-kubernetes
    namespace: default
```

**Comment by hasheddan** [comment]
> Is this new functionality that we should be documenting in this repo? If so, I am thinking it's totally fine for it to be a separate PR.

@suskin I think the only place this is talked about is in the [stacks-guide](https://crossplane.io/docs/v0.7/stacks-guide.html), and it doesn't use any of the `spec` fields, so we should be good. I took a quick pass through those docs and everything appears to still be accurate :+1: 

> Did we already test to make sure none of the other functionality has regressed? (As in, provisioning by binding with configured classes.)

@suskin This functionality should not be affected at all as the `KubernetesTarget` auto-creation controller is agnostic about when the `KubernetesCluster` is created. If the `kubernetesClusterRef` was omitted from the config above, the Wordpress controller would just create the `KubernetesCluster` and when it became bound, a `KubernetesTarget` would automatically be created with the labels of the `KubernetesCluster`, so scheduling would proceed as expected.

> Suggest changing `kubernetesClusterRef` this to `kubernetesTargetRef` here.

@prasek  This change is logically unrelated to the update made in this PR (and also more complex), so I will follow with an issue describing the change and then a subsequent PR if the proposal in the issue is ratified.

Going to go ahead and merge this with the provided approvals :heavy_check_mark:

**Pull request merged**
