### PR TITLE
Delete KubernetesApplication first

### PR DESCRIPTION
**Pull request by muvaf**
Delete KubernetesApplication before others so that the Service in the remote cluster is deleted before the cluster is destroyed.

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
@muvaf this LGTM! We could cut a new templating controller and pin it here but doing that in a follow up sounds fine as well

**Comment by muvaf** [comment]
@hasheddan I think that will be part of the release process? I though about bumping it to `0.3.1` but it didn't make much sense to release for one PR if there is a release cadence already.

**Comment by hasheddan** [comment]
@muvaf yeah I was thinking we would be releasing out of sync with Crossplane here, but we may be waiting so I’m fine with this moving ahead :)

**Comment by prasek** [comment]
> @muvaf yeah I was thinking we would be releasing out of sync with Crossplane here, but we may be waiting so I’m fine with this moving ahead :)

@hasheddan @muvaf  Would be fine moving ahead with `0.3.1` as well, so we can test this e2e with `app-wordpress` before the umbrella release goes out.

**Pull request merged**
